[project]
name = "1st"
version = "0.1.0"
description = "Starter Project"
authors = [
    {name = "Mark",email = "pythondev677@gmail.com"}
]
license = {text = "none"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kivy (>=2.3.1,<3.0.0)",
    "kivymd (>=1.2.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
